Repository EdikyLab/ediky-website, pull requests merged in 2025-05, with the labels that each got.

#39 changed the overall look of the starting page(phase-2)
  mlorbit_frontend/package-lock.json
  mlorbit_frontend/package.json
  mlorbit_frontend/public/index.html
  mlorbit_frontend/public/logo192.png
  mlorbit_frontend/public/logo512.png
  mlorbit_frontend/src/App.css
  mlorbit_frontend/src/App.js
  mlorbit_frontend/src/components/AsciiThreeText.css
  mlorbit_frontend/src/components/AsciiThreeText.jsx
  mlorbit_frontend/src/components/CircularGallery.css
  mlorbit_frontend/src/components/CircularGallery.jsx
  mlorbit_frontend/src/components/DarkModeToggle.css
  mlorbit_frontend/src/components/DarkModeToggle.js
  mlorbit_frontend/src/components/FuzzyText.jsx
  mlorbit_frontend/src/components/GlitchText.css
  mlorbit_frontend/src/components/GlitchText.jsx
  mlorbit_frontend/src/components/InfiniteMenu.css
  mlorbit_frontend/src/components/InfiniteMenu.jsx
  mlorbit_frontend/src/components/Navbar.css
  mlorbit_frontend/src/components/Navbar.js
  mlorbit_frontend/src/components/Sections.css
  mlorbit_frontend/src/components/Spinner.css
  mlorbit_frontend/src/components/WelcomeSection.css
  mlorbit_frontend/src/components/WelcomeSection.jsx
  mlorbit_frontend/src/index.css
Labels: enhancement, javascript, Priority-High

#40 Made some more changes in the home page
  mlorbit_frontend/package-lock.json
  mlorbit_frontend/package.json
  mlorbit_frontend/src/App.js
  mlorbit_frontend/src/components/BallPit.jsx
  mlorbit_frontend/src/components/Footer.css
  mlorbit_frontend/src/components/Footer.jsx
  mlorbit_frontend/src/components/button.css
  mlorbit_frontend/src/components/button.jsx
  mlorbit_frontend/src/components/devops.css
  mlorbit_frontend/src/components/devops.jsx
Labels: enhancement, feature

#41 Changed the overall look of the login page
  mlorbit_frontend/src/login/LoginPage.css
  mlorbit_frontend/src/login/LoginPage.js
  mlorbit_frontend/src/login/LoginPage.jsx
  mlorbit_frontend/src/login/PrivateRoute.jsx
  mlorbit_frontend/src/login/ShapeBlur.jsx
Labels: enhancement, Priority-High

#42 removed the unnecessary Readme.md
  mlorbit_frontend/README.md
Labels: documentation

#43 minor changes
  mlorbit_frontend/env.example
  mlorbit_frontend/src/components/Navbar.js
  mlorbit_frontend/src/components/WelcomeSection.jsx
Labels: Priority-Low, minor-change

#44 Addition of a comprehensive doc section with many utilities
  mlorbit_frontend/.npmrc
  mlorbit_frontend/package-lock.json
  mlorbit_frontend/package.json
  mlorbit_frontend/public/docs/deep-learning/cnns.md
  mlorbit_frontend/public/docs/deep-learning/index.md
  mlorbit_frontend/public/docs/deep-learning/rnns.md
  mlorbit_frontend/public/docs/machine-learning/classification.md
  mlorbit_frontend/public/docs/machine-learning/index.md
  mlorbit_frontend/public/docs/machine-learning/regression.md
  mlorbit_frontend/public/docs/natural-language-processing/index.md
  mlorbit_frontend/public/docs/natural-language-processing/tokenisation.md
  mlorbit_frontend/public/docs/reinforcement-learning/index.md
  mlorbit_frontend/public/index.html
  mlorbit_frontend/src/App.js
  mlorbit_frontend/src/components/button.jsx
  mlorbit_frontend/src/docViewer/CodePlayground.css
  mlorbit_frontend/src/docViewer/CodePlayground.jsx
  mlorbit_frontend/src/docViewer/DocsSidebar.css
  mlorbit_frontend/src/docViewer/DocsSidebar.jsx
  mlorbit_frontend/src/docViewer/HighlightableText.css
  mlorbit_frontend/src/docViewer/HighlightableText.jsx
  mlorbit_frontend/src/docViewer/MarkdownContent.css
  mlorbit_frontend/src/docViewer/MarkdownContent.jsx
  mlorbit_frontend/src/docViewer/SpeechReader.css
  mlorbit_frontend/src/docViewer/SpeechReader.jsx
  mlorbit_frontend/src/docViewer/docs.css
  mlorbit_frontend/src/docViewer/sections.json
  mlorbit_frontend/src/pages/DocsPage.css
  mlorbit_frontend/src/pages/DocsPage.jsx
Labels: documentation, enhancement, Priority-High

#45 Update Footer.css
  mlorbit_frontend/src/components/Footer.css
Labels: minor-change

#48 Create node.js.yml
  .github/workflows/node.js.yml
Labels: enhancement, CI-CD

#51 Update package.json
  mlorbit_frontend/package.json
Labels: dependencies

#55 Update SECURITY.md
  SECURITY.md
Labels: minor-change

#53 Update Versions
  mlorbit_frontend/.npmrc
  mlorbit_frontend/package-lock.json
  mlorbit_frontend/package.json
Labels: dependencies
