Repository EdikyLab/ediky-website, pull requests merged in 2025-08, with the labels that each got.

#65 Update README.md
  README.md
Labels: documentation

#67 major clean up, will start work once everything is clean
  ediky_front/.gitignore
  ediky_front/.npmrc
  ediky_front/env.example
  ediky_front/package-lock.json
  ediky_front/package.json
  ediky_front/public/_redirects
  ediky_front/public/ediky_logo.svg
  ediky_front/public/index.html
  ediky_front/public/manifest.json
  ediky_front/public/robots.txt
  ediky_front/src/App.css
  ediky_front/src/App.js
  ediky_front/src/App.test.js
  ediky_front/src/ErrorBoundary.js
  ediky_front/src/assets/algos.jpg
  ediky_front/src/assets/datastructures.jpg
  ediky_front/src/assets/giphy.gif
  ediky_front/src/assets/jett.jpg
  ediky_front/src/assets/logo.jpg
  ediky_front/src/assets/logo.svg
  ediky_front/src/assets/minecraft.jpg
  ediky_front/src/assets/ml.jpg
  ediky_front/src/assets/space1.jpg
  ediky_front/src/assets/space2.jpg
  ediky_front/src/components/AboutSection.css
  ediky_front/src/components/AboutSection.js
  ediky_front/src/components/AsciiThreeText.css
  ediky_front/src/components/AsciiThreeText.jsx
  ediky_front/src/components/Footer.css
  ediky_front/src/components/Footer.jsx
  ediky_front/src/components/Navbar.css
  ediky_front/src/components/Navbar.js
  ediky_front/src/components/PrivateRoute.jsx
  ediky_front/src/components/Sections.css
  ediky_front/src/components/Sections.js
  ediky_front/src/components/Spinner.css
  ediky_front/src/components/Spinner.jsx
  ediky_front/src/components/ThemeToggle.js
  ediky_front/src/components/WelcomeSection.css
  ediky_front/src/components/WelcomeSection.jsx
  ediky_front/src/components/userDetails/UserContext.js
  ediky_front/src/context/UserContext.js
  ediky_front/src/index.css
  ediky_front/src/index.js
  ediky_front/src/login/AuthContext.js
  ediky_front/src/login/AuthService.js
  ediky_front/src/login/LoginPage.css
  ediky_front/src/login/LoginPage.jsx
  ediky_front/src/login/PrivateRoute.jsx
  ediky_front/src/login/ShapeBlur.jsx
  ediky_front/src/login/firebaseConfig.js
  ediky_front/src/logo.svg
  ediky_front/src/reportWebVitals.js
  ediky_front/src/setupTests.js
Labels: documentation, enhancement, Priority-High

#75 add the new doc section with some features
  ediky_front/package-lock.json
  ediky_front/package.json
  ediky_front/public/docs/api.md
  ediky_front/public/docs/getting-started.md
  ediky_front/public/docs/intro.md
  ediky_front/public/docs/manifest.json
  ediky_front/public/manifest.json
  ediky_front/src/App.js
  ediky_front/src/components/Navbar.jsx
  ediky_front/src/pages/Docs.css
  ediky_front/src/pages/DocsPage.jsx
  ediky_front/src/pages/docStore.js
Labels: documentation, enhancement, dependencies

#77 Update README.md
  README.md
  package-lock.json
Labels: documentation, minor-change

#78 add Pull Request and Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/workflows/ci.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CI-CD
